project_id = "rzckgajxdksecstoeasl"

[functions.fetch-stocks-data]
verify_jwt = false

[functions.fetch-crypto-data]
verify_jwt = false

[functions.fetch-metals-data]
verify_jwt = false

[functions.fetch-bond-data]
verify_jwt = false

[functions.fetch-cyprus-housing]
verify_jwt = false

[functions.fetch-economic-data]
verify_jwt = false

[functions.fetch-btc-macro-data]
verify_jwt = false

[functions.check-api-health]
verify_jwt = false

[functions.sync-wallet-balance]
verify_jwt = true

[functions.sync-exchange-balance]
verify_jwt = true

[functions.parse-portfolio-csv]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

[functions.crypto-market-analysis]
verify_jwt = true

[functions.overall-market-analysis]
verify_jwt = true

[functions.risk-forecast]
verify_jwt = true

[functions.portfolio-analysis]
verify_jwt = true